"""Post-process AEH-generated Harbor task packages for OpenShift runs.

Upstream ``agent_eval.harbor.tasks.generate_tasks`` (v1.0.3) omits:

1. ``annotations.yaml`` in ``environment/`` and blanks ``dataset.path``, so
   Harbor verifiers cannot load judge annotations (``case_dir`` is the
   workdir basename, typically ``workspace``).
2. Submission ``plugin_dirs`` / ``skills/`` trees, so Claude Code gets
   ``Unknown command: /<skill>`` when the instruction uses a slash-skill.

This module patches generated task packages in-place before ``harbor run``.
It does not modify upstream agent-eval-harness source.

Tool interception / MCP hooks generated by AEH into ``environment/hooks/``,
``environment/tool_handlers.yaml``, and ``environment/.claude/settings.json``
are preserved. If ``generate_tasks`` skipped them, submission-level
``tool_handlers.yaml`` is copied into each task ``environment/``.
"""

from __future__ import annotations

import logging
import re
import shutil
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

_ANNOTATIONS_STAGE = """
# ABEvalFlow: stage annotations for Harbor verifier judges.
# reward.py uses case_dir basename (e.g. "workspace") under dataset.path.
if [ -f "@@WORKDIR@@/annotations.yaml" ]; then
  _aeh_case="$(basename "@@WORKDIR@@")"
  mkdir -p "/tests/cases/${_aeh_case}"
  cp "@@WORKDIR@@/annotations.yaml" "/tests/cases/${_aeh_case}/annotations.yaml"
fi
""".lstrip()

# Artifacts produced by agent_eval.harbor.tasks._generate_tool_interception
_INTERCEPTION_MARKERS = (
    "hooks/tools.py",
    "tool_handlers.yaml",
    ".claude/settings.json",
)


def enrich_harbor_tasks(
    tasks_dir: Path,
    *,
    config_path: Path,
    skill_model: str | None = None,
    judge_model: str | None = None,
) -> int:
    """Enrich every Harbor task package under *tasks_dir*.

    Optional *skill_model* / *judge_model* rewrite ``models`` in each task's
    bundled ``tests/eval.yaml`` (in-pod judges read this file). When the
    submission has no ``reward:`` section, inject a weighted formula over
    declared judges so all-null judge values yield 0.0 instead of AEH's
    default 1.0.

    Returns the number of task packages updated.
    """
    config_path = Path(config_path)
    tasks_dir = Path(tasks_dir)
    if not tasks_dir.is_dir():
        return 0

    raw = yaml.safe_load(config_path.read_text()) or {}
    if not isinstance(raw, dict):
        raw = {}
    submission_root = config_path.parent
    dataset_rel = ""
    dataset = raw.get("dataset") or {}
    if isinstance(dataset, dict):
        dataset_rel = str(dataset.get("path") or "").strip()

    plugin_dirs: list[str] = []
    runner = raw.get("runner") or {}
    if isinstance(runner, dict):
        plugin_dirs = list(runner.get("plugin_dirs") or [])

    wants_interception = _config_wants_tool_interception(raw)
    reward_inject = _reward_to_inject(raw)

    updated = 0
    for task_dir in sorted(p for p in tasks_dir.iterdir() if p.is_dir()):
        if not (task_dir / "task.toml").is_file():
            continue
        _enrich_one_task(
            task_dir,
            case_id=task_dir.name,
            submission_root=submission_root,
            dataset_rel=dataset_rel,
            plugin_dirs=plugin_dirs,
            config_path=config_path,
            wants_interception=wants_interception,
            skill_model=skill_model,
            judge_model=judge_model,
            reward_inject=reward_inject,
        )
        updated += 1
    return updated


def _reward_to_inject(raw: dict) -> dict | None:
    """Build a weighted reward block when the submission omits ``reward:``."""
    if isinstance(raw.get("reward"), dict) and raw["reward"]:
        return None
    judges = raw.get("judges") or []
    if not isinstance(judges, list):
        return None
    names = [
        str(j["name"])
        for j in judges
        if isinstance(j, dict) and j.get("name")
    ]
    if not names:
        return None
    return {
        "formula": "weighted",
        "weights": {name: 1.0 for name in names},
    }


def _config_wants_tool_interception(raw: dict) -> bool:
    inputs = raw.get("inputs") or {}
    if isinstance(inputs, dict):
        tools = inputs.get("tools") or []
        if isinstance(tools, list) and tools:
            return True
    permissions = raw.get("permissions") or {}
    if isinstance(permissions, dict) and (permissions.get("deny") or permissions.get("allow")):
        return True
    return False


def _enrich_one_task(
    task_dir: Path,
    *,
    case_id: str,
    submission_root: Path,
    dataset_rel: str,
    plugin_dirs: list[str],
    config_path: Path,
    wants_interception: bool,
    skill_model: str | None = None,
    judge_model: str | None = None,
    reward_inject: dict | None = None,
) -> None:
    env_dir = task_dir / "environment"
    env_dir.mkdir(parents=True, exist_ok=True)
    tests_dir = task_dir / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)

    # Snapshot interception artifacts before any destructive copies
    preserved = _snapshot_interception(env_dir)

    # 1) annotations.yaml → environment/ (uploaded to workdir)
    annotations_src = _find_annotations(submission_root, dataset_rel, case_id)
    if annotations_src is not None:
        shutil.copy2(annotations_src, env_dir / "annotations.yaml")

    # 2) Patch bundled eval.yaml: dataset.path, models, reward hardening
    bundled = tests_dir / "eval.yaml"
    if bundled.is_file():
        cfg = yaml.safe_load(bundled.read_text()) or {}
        if not isinstance(cfg, dict):
            cfg = {}
        if isinstance(cfg.get("dataset"), dict):
            cfg["dataset"]["path"] = "cases"
        elif "dataset" not in cfg:
            cfg["dataset"] = {"path": "cases"}
        if skill_model or judge_model:
            models = cfg.get("models")
            if not isinstance(models, dict):
                models = {}
                cfg["models"] = models
            if skill_model:
                models["skill"] = skill_model
            if judge_model:
                models["judge"] = judge_model
        if reward_inject is not None and not (
            isinstance(cfg.get("reward"), dict) and cfg["reward"]
        ):
            cfg["reward"] = reward_inject
        bundled.write_text(yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True))

    # 3) Stage annotations in test.sh before reward runs
    test_sh = tests_dir / "test.sh"
    if test_sh.is_file():
        _inject_annotations_stage(test_sh)

    # 4) Copy plugin skill trees + point Harbor at them
    #    Only replace environment/skills/ — never wipe hooks/ or .claude/
    copied_skills = False
    for rel in plugin_dirs:
        src = (submission_root / rel).resolve()
        if not src.is_dir():
            continue
        if not _dir_has_skill_md(src):
            continue
        dest = env_dir / "skills"
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(src, dest)
        copied_skills = True
        break  # Harbor expects a single skills_dir root

    if copied_skills:
        _ensure_skills_dir_in_task_toml(task_dir / "task.toml", "/workspace/skills")

    # 5) Restore / ensure tool interception + MCP hook artifacts
    _restore_interception(env_dir, preserved)
    _ensure_submission_tool_handlers(env_dir, config_path)
    if wants_interception and not _has_interception(env_dir):
        logger.warning(
            "Task %s: eval.yaml declares inputs.tools/permissions but environment/ "
            "has no hooks/tools.py or tool_handlers.yaml — Harbor will not intercept tools",
            task_dir.name,
        )


def _snapshot_interception(env_dir: Path) -> dict[str, bytes]:
    """Read interception files so enrichment cannot accidentally drop them."""
    snapped: dict[str, bytes] = {}
    for rel in _INTERCEPTION_MARKERS:
        path = env_dir / rel
        if path.is_file():
            snapped[rel] = path.read_bytes()
    return snapped


def _restore_interception(env_dir: Path, preserved: dict[str, bytes]) -> None:
    for rel, data in preserved.items():
        dest = env_dir / rel
        if dest.is_file():
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)


def _ensure_submission_tool_handlers(env_dir: Path, config_path: Path) -> None:
    """Copy submission-level tool_handlers.yaml into environment/ when missing."""
    dest = env_dir / "tool_handlers.yaml"
    if dest.is_file():
        return
    src = config_path.parent / "tool_handlers.yaml"
    if src.is_file():
        shutil.copy2(src, dest)


def _has_interception(env_dir: Path) -> bool:
    return (env_dir / "hooks" / "tools.py").is_file() or (env_dir / "tool_handlers.yaml").is_file()


def _find_annotations(submission_root: Path, dataset_rel: str, case_id: str) -> Path | None:
    candidates: list[Path] = []
    if dataset_rel:
        candidates.append(submission_root / dataset_rel / case_id / "annotations.yaml")
    candidates.append(submission_root / "cases" / case_id / "annotations.yaml")
    for path in candidates:
        if path.is_file():
            return path
    return None


def _dir_has_skill_md(skills_root: Path) -> bool:
    if (skills_root / "SKILL.md").is_file():
        return True
    for child in skills_root.iterdir():
        if child.is_dir() and (child / "SKILL.md").is_file():
            return True
    return False


def _inject_annotations_stage(test_sh: Path) -> None:
    text = test_sh.read_text()
    if "ABEvalFlow: stage annotations" in text:
        return

    workdir = "/workspace"
    m = re.search(r'--case-dir\s+"([^"]+)"', text)
    if m:
        workdir = m.group(1)
    stage = _ANNOTATIONS_STAGE.replace("@@WORKDIR@@", workdir)

    marker = "mkdir -p /logs/verifier"
    if marker in text:
        text = text.replace(marker, marker + "\n\n" + stage, 1)
    else:
        text = stage + "\n" + text
    test_sh.write_text(text)


def _ensure_skills_dir_in_task_toml(task_toml: Path, skills_dir: str) -> None:
    text = task_toml.read_text()
    if re.search(r"^\s*skills_dir\s*=", text, flags=re.MULTILINE):
        return
    if re.search(r'^\s*workdir\s*=\s*"[^"]*"', text, flags=re.MULTILINE):
        text = re.sub(
            r'^(\s*workdir\s*=\s*"[^"]*")\s*$',
            rf'\1\nskills_dir = "{skills_dir}"',
            text,
            count=1,
            flags=re.MULTILINE,
        )
    else:
        text = text.rstrip() + f'\n\n[environment]\nskills_dir = "{skills_dir}"\n'
    task_toml.write_text(text)
