FROM registry.access.redhat.com/ubi9/python-311:latest

USER 0
RUN curl -LsSf https://astral.sh/uv/0.9.7/install.sh | env UV_INSTALL_DIR=/usr/local/bin sh
USER 1001

WORKDIR /workspace

COPY instruction.md .
COPY tests/ /tests/
{% if has_supportive %}
COPY supportive/ /workspace/supportive/
{% endif %}
{% if has_scripts %}
COPY scripts/ /workspace/scripts/
{% endif %}
{% for src, dest in copy_pairs %}
COPY {{ src }}/ {{ dest }}/
{% endfor %}
